### ISSUE TITLE
Add lines to .npmrc

### ISSUE THREAD

**Issue by map7** [heroqu/ansible-nodejs4x#1]
I'm installing this onto a fresh installation of Debian 8.3 jessie and I get this error

```
TASK: [Heroqu.nodejs4x | Add lines to .npmrc] ********************************* 
failed: [192.168.200.215] => (item={'regexp': '^prefix\\s*=', 'line': 'prefix=~/.npm-packages', 'state': 'present'}) => {"failed": true, "item": {"line": "prefix=~/.npm-packages", "regexp": "^prefix\\s*=", "state": "present"}, "parsed": false}
Sorry, user map7 is not allowed to execute '/bin/sh -c echo BECOME-SUCCESS-rvhknysgokbkqvfyexbuenjeqrndkcsd; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /tmp/ansible-tmp-1456353173.02-181597325667470/lineinfile' as map7 on debian.

```

Here is my playbook

```

---
# Webserver for running Ruby on Rails with postgresql & node.
# Run
# ansible-playbook webserver.yml -v

- hosts: webservers
  user: map7

  roles:
    - role: Heroqu.nodejs4x
```

**Comment by heroqu** [comment]
Hi, Michael!

thank you for noting this bug. 

It is not related to the box, Debian/Jessie64 box works fine actually, I've just check with local setup Vagrant+Ansible+VirtualBox.

My guess is the problem is with special user you use and somehow it is not configured properly as sudoer for the operation used in my role. So, I shouldn't have to rely on the premise. 

I've just uploaded the fix, which essentially does get rid of using sudoing as deploy user, and instead doing regular sudo while editing the ~/.npmrc file. I've just made sure that the owner and group of the file do belong to deploy user.

Hope that should work out.

Sergey
